-- Data fix: truncate invalid passport data before applying VARCHAR limits
UPDATE "Customer" SET "passportSeries" = LEFT("passportSeries", 4) WHERE LENGTH("passportSeries") > 4;
UPDATE "Customer" SET "passportNumber" = LEFT("passportNumber", 6) WHERE "passportNumber" IS NOT NULL AND LENGTH("passportNumber") > 6;

-- DropForeignKey
ALTER TABLE "MotivationAssignment" DROP CONSTRAINT "MotivationAssignment_userId_fkey";

-- DropForeignKey
ALTER TABLE "UserRole" DROP CONSTRAINT "UserRole_userId_fkey";

-- DropForeignKey
ALTER TABLE "UserStore" DROP CONSTRAINT "UserStore_userId_fkey";

-- AlterTable
ALTER TABLE "AuditLog" ALTER COLUMN "action" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "entity" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "entityId" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Brand" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "CashOperation" ALTER COLUMN "reason" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "CustomOrder" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "clientName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "clientPhone" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "clientEmail" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "supplierCity" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "trackingInfo" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "cancellationType" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "cancelReason" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "CustomOrderItem" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "imei" SET DATA TYPE VARCHAR(15);

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "passportSeries" SET DATA TYPE VARCHAR(4),
ALTER COLUMN "passportNumber" SET DATA TYPE VARCHAR(6),
ALTER COLUMN "passportIssuedBy" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "DeviceRecord" ALTER COLUMN "imei" SET DATA TYPE VARCHAR(15),
ALTER COLUMN "imei2" SET DATA TYPE VARCHAR(15),
ALTER COLUMN "serialNumber" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "brand" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "model" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "DocumentTemplate" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "Fund" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "InventoryAudit" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "InventoryAuditSerial" ALTER COLUMN "scannedImei" SET DATA TYPE VARCHAR(15);

-- AlterTable
ALTER TABLE "MotivationAssignment" ALTER COLUMN "userId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MotivationGroup" ALTER COLUMN "code" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "MotivationScheme" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "rejectionReason" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "OrderStatusHistory" ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Permission" ALTER COLUMN "code" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "module" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "PriceHistory" ALTER COLUMN "field" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "PriceLabelTemplate" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "sku" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "barcode" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "unit" SET DATA TYPE VARCHAR(20);

-- AlterTable
ALTER TABLE "Repair" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "clientName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "clientPhone" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "deviceType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceBrand" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceModel" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceSerial" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceCondition" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "devicePassword" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "defectDescription" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "diagnosis" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "workDone" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "RepairCostHistory" ALTER COLUMN "field" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "RepairStatusHistory" ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Return" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "reason" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Sale" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "SaleItem" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "SerialUnit" ALTER COLUMN "imei" SET DATA TYPE VARCHAR(15),
ALTER COLUMN "imei2" SET DATA TYPE VARCHAR(15),
ALTER COLUMN "serialNumber" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "SerialUnitHistory" ALTER COLUMN "relatedDocument" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Shift" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "note" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "StockReceive" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "StockTransfer" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "StockWriteOff" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "reason" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "StockWriteOffItem" ALTER COLUMN "writeOffReason" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "Store" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "address" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20);

-- AlterTable
ALTER TABLE "Supplier" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "contactName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "website" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "city" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "address" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "inn" SET DATA TYPE VARCHAR(12),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "SupplierDebt" ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "SupplierPayment" ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "TradeIn" ALTER COLUMN "number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "deviceType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceBrand" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceModel" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "deviceImei" SET DATA TYPE VARCHAR(15),
ALTER COLUMN "deviceCondition" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "comment" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "login" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "password" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20);

-- AlterTable
ALTER TABLE "UserRole" ALTER COLUMN "userId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "UserStore" ALTER COLUMN "userId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "WarrantyClaim" ALTER COLUMN "description" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "resolution" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "number" SET DATA TYPE VARCHAR(50);

-- AddForeignKey
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserStore" ADD CONSTRAINT "UserStore_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MotivationAssignment" ADD CONSTRAINT "MotivationAssignment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

